# Generated by Django 4.2.11 on 2025-05-16 01:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference_created_at_userpreference_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_picture_path, validators=[users.models.validate_image_size]),
        ),
    ]
