# Generated by Django 4.2.11 on 2025-05-16 11:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_board_id_alter_column_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=projects.models.get_today),
        ),
    ]
