# Generated by Django 4.2.11 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('project',), name='one_default_board_per_project'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.CheckConstraint(check=models.Q(('wip_limit__gt', 0), ('wip_limit__isnull', True), _connector='OR'), name='positive_wip_limit'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_column_name_per_board'),
        ),
    ]
