version: '3.8'

services:

  # Django application
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: unless-stopped
    volumes:
      - sqlite_data:/data
      - static_data:/app/staticfiles
      - media_data:/app/media
    entrypoint: ["/app/build.sh", "docker"]
    env_file:
      - .env
    # Add environment variables not in .env file
    environment:
      - DJANGO_SETTINGS_MODULE=projectmanagement.settings
      - DATABASE_PATH=/data/db.sqlite3
      # Superuser credentials for first run (only used if superuser doesn't exist)
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-adminpassword}
    ports:
      - "80:8000"
    networks:
      - app_network
    # Set memory and CPU limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M



networks:
  app_network:
    driver: bridge

volumes:
  sqlite_data:
  static_data:
  media_data:
