services:
  - type: web
    name: projectmanagement-backend
    env: python
    plan: free
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: >-
      if [ -z "$DJANGO_SUPERUSER_PASSWORD" ]; then
        echo "Warning: DJANGO_SUPERUSER_PASSWORD is not set. Skipping superuser creation."
      else
        python manage.py create_superuser --noinput \
          --username=${DJANGO_SUPERUSER_USERNAME} \
          --email=${DJANGO_SUPERUSER_EMAIL} \
          --password=${DJANGO_SUPERUSER_PASSWORD} || true
      fi && \
      gunicorn projectmanagement.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: projectmanagement.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: projectmanagement-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: projectmanagement-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: projectmanagement-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://projectmanagement-frontend.onrender.com,http://localhost:3000
      - key: ALLOWED_HOSTS
        value: projectmanagement-backend.onrender.com,localhost,127.0.0.1
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      - key: SECURE_PROXY_SSL_HEADER
        value: "HTTP_X_FORWARDED_PROTO,https"
    healthCheckPath: /api/health/
    autoDeploy: yes

  - type: web
    name: projectmanagement-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm ci --prefer-offline --no-audit --progress=false
      npm run build:ci
    staticPublishPath: ./frontend/build
    startCommand: 'serve -s build -l $PORT'
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: REACT_APP_API_URL
        value: https://projectmanagement-backend.onrender.com
      - key: CI
        value: "false"
      - key: REACT_APP_WS_URL
        value: 'wss://projectmanagement-backend.onrender.com/ws/'
    plan: free

  - type: redis
    name: projectmanagement-redis
    plan: free
    ipAllowList: []  # Allow all IPs by default

databases:
  - name: projectmanagement-db
    databaseName: projectmanagement
    user: projectmanagement
    plan: free
