services:
  - type: web
    name: projectmanagement-backend
    env: python
    plan: free
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: >-
      python manage.py create_superuser --noinput \
        --username=${DJANGO_SUPERUSER_USERNAME} \
        --email=${DJANGO_SUPERUSER_EMAIL} \
        --password=${DJANGO_SUPERUSER_PASSWORD} || true && \
      gunicorn projectmanagement.wsgi:application --log-file - --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: projectmanagement.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: 'projectmanagement-backend.onrender.com,projectmanagement.onrender.com,localhost,127.0.0.1'
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: FRONTEND_URL
        value: 'https://projectmanagement.onrender.com'
      - key: CELERY_BROKER_URL
        fromService:
          name: projectmanagement-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: projectmanagement-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: projectmanagement-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: projectmanagement-redis
          type: redis
          property: connectionString
      - key: DJANGO_STATIC_ROOT
        value: '/var/www/static/'
      - key: DJANGO_MEDIA_ROOT
        value: '/var/www/media/'
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: 'https://projectmanagement-backend.onrender.com https://projectmanagement.onrender.com'

  - type: web
    name: projectmanagement-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: 'serve -s build -l $PORT'
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: REACT_APP_API_URL
        value: 'https://projectmanagement-backend.onrender.com/api/v1'
      - key: REACT_APP_WS_URL
        value: 'wss://projectmanagement-backend.onrender.com/ws/'
    plan: free

  - type: redis
    name: projectmanagement-redis
    plan: free
    ipAllowList: []  # Allow all IPs by default

databases:
  - name: projectmanagement-db
    databaseName: projectmanagement
    user: projectmanagement
    plan: free
