services:
  - type: web
    name: projectmanagement
    env: docker
    plan: free
    dockerfilePath: Dockerfile.backend
    dockerContext: .
    dockerCommand: "gunicorn projectmanagement.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectmanagement.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
    autoDeploy: true
