services:
  - type: web
    name: projectmanagement
    env: python
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh build
    startCommand: ./build.sh django
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: projectmanagement.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/db.sqlite3
      - key: RENDER
        value: "true"
      # Simplified architecture - WebSockets and background tasks removed
      - key: ALLOWED_HOSTS
        value: projectmanagement-c23m.onrender.com,localhost,127.0.0.1,.onrender.com
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      # Email configuration (using SendGrid)
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.sendgrid.net
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: apikey
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Set your SendGrid API key in Render dashboard
      - key: DEFAULT_FROM_EMAIL
        value: noreply@yourdomain.com
