services:
  - type: web
    name: projectmanagement
    env: python
    plan: free
    buildCommand: chmod +x ./build.sh ./superuser.sh && ./build.sh build
    startCommand: |
      ./superuser.sh && ./build.sh django
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: projectmanagement.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/db.sqlite3
      # Celery and Redis dependencies have been removed
      - key: ALLOWED_HOSTS
        value: projectmanagement-c23m.onrender.com,localhost,127.0.0.1,.onrender.com
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
