from setuptools import setup, find_packages

setup(
    name="projectmanagement",
    version="1.0.0",
    description="A Trello/Asana-like project management application with real-time collaboration",
    author="Project Management Team",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=4.2.11,<4.3",
        "asgiref>=3.7.2",
        "sqlparse>=0.4.4",
        "python-dotenv>=1.0.1",
        "djangorestframework>=3.14.0",
        "django-cors-headers>=4.3.1",
        "djoser>=2.2.2",
        "djangorestframework-simplejwt>=5.3.0",
        "django-filter>=23.5",
        "drf-yasg>=1.21.7",
        "drf-nested-routers>=0.95.0",
        "channels>=4.0.0",
        "daphne>=4.0.0",
        "channels-redis>=4.1.0",
        "celery>=5.3.6",
        "redis>=5.0.1",
        "Pillow>=10.1.0",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 4.2",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Office/Business :: Groupware",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
) 