# Generated by Django 4.2.11 on 2025-05-26 05:24

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_label_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=tasks.models.secure_attachment_path, validators=[tasks.models.validate_attachment_file]),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='attachment_file_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('estimated_hours__gt', 0), ('estimated_hours__isnull', True), _connector='OR'), name='task_estimated_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('actual_hours__gt', 0), ('actual_hours__isnull', True), _connector='OR'), name='task_actual_hours_positive'),
        ),
    ]
