# Generated by Django 4.2.11 on 2025-05-16 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activitylogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activitylog_user_id_784699_idx',
            old_name='activitylog_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activitylog_action__7cfe0b_idx',
            old_name='activitylog_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activitylog_timesta_4bebc8_idx',
            old_name='activitylog_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activitylog_content_a08349_idx',
            old_name='activitylog_content_object_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activitylog_project_9a873d_idx',
            old_name='activitylog_project_id_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activitylogs_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
