# Generated by Django 5.2.1 on 2025-05-14 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('deadline_approaching', 'Deadline Approaching'), ('deadline_missed', 'Deadline Missed'), ('comment_added', 'Comment Added'), ('mentioned', 'Mentioned'), ('project_added', 'Project Added'), ('invitation', 'Invitation')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.BooleanField(default=True)),
                ('task_updated', models.BooleanField(default=True)),
                ('deadline_approaching', models.BooleanField(default=True)),
                ('deadline_missed', models.BooleanField(default=True)),
                ('comment_added', models.BooleanField(default=True)),
                ('mentioned', models.BooleanField(default=True)),
                ('project_added', models.BooleanField(default=True)),
                ('invitation', models.BooleanField(default=True)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_updated', models.BooleanField(default=False)),
                ('email_deadline_approaching', models.BooleanField(default=True)),
                ('email_deadline_missed', models.BooleanField(default=True)),
                ('email_comment_added', models.BooleanField(default=False)),
                ('email_mentioned', models.BooleanField(default=True)),
                ('email_project_added', models.BooleanField(default=True)),
                ('email_invitation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
